// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compute_GCD
int compute_GCD(int a, int b);
RcppExport SEXP DescTools_compute_GCD(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    __result = Rcpp::wrap(compute_GCD(a, b));
    return __result;
END_RCPP
}
// compute_LCM
int compute_LCM(int a, int b);
RcppExport SEXP DescTools_compute_LCM(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    __result = Rcpp::wrap(compute_LCM(a, b));
    return __result;
END_RCPP
}
// n_pow_sum
List n_pow_sum(NumericVector x, double meanx);
RcppExport SEXP DescTools_n_pow_sum(SEXP xSEXP, SEXP meanxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type meanx(meanxSEXP);
    __result = Rcpp::wrap(n_pow_sum(x, meanx));
    return __result;
END_RCPP
}
// conv_DecToBin
std::vector< std::string > conv_DecToBin(std::vector< int > n);
RcppExport SEXP DescTools_conv_DecToBin(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< int > >::type n(nSEXP);
    __result = Rcpp::wrap(conv_DecToBin(n));
    return __result;
END_RCPP
}
