# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_GCD <- function(a, b) {
    .Call(`_DescTools_compute_GCD`, a, b)
}

compute_LCM <- function(a, b) {
    .Call(`_DescTools_compute_LCM`, a, b)
}

n_pow_sum <- function(x) {
    .Call(`_DescTools_n_pow_sum`, x)
}

conv_DecToBin <- function(n) {
    .Call(`_DescTools_conv_DecToBin`, n)
}

top_n <- function(x, n = 5L) {
    .Call(`_DescTools_top_n`, x, n)
}

bottom_n <- function(x, n = 5L) {
    .Call(`_DescTools_bottom_n`, x, n)
}

top_i <- function(v, n) {
    .Call(`_DescTools_top_i`, v, n)
}

bottom_i <- function(v, n) {
    .Call(`_DescTools_bottom_i`, v, n)
}

